library("ggGenshin")
library("ggplot2")
library("reshape2")
library("dplyr")

dat1 = aggregate(iris[, 1:4], by = list(iris$Species), mean) %>%
	melt() %>%
	rename(species = Group.1)
p1 = ggplot(dat1) +
	geom_col(aes(x = variable, y = value, fill = species), position = "dodge") +
	theme_test()

dat2 = iris[, c(5, 1, 2, 3)]
p2 = ggplot(dat2) +
	geom_point(aes(x = Sepal.Length, y = Sepal.Width, color = Petal.Length), size = 3) +
	theme_test()

if(dir.exists("out") == FALSE){
	dir.create("out")
}

ggsave("out/albedo1.png", p1 + scale_fill_albedo(), width = 6, height = 3)
ggsave("out/albedo2.png", p2 + scale_color_albedo(F), width = 6, height = 3)
ggsave("out/alhaitham1.png", p1 + scale_fill_alhaitham(), width = 6, height = 3)
ggsave("out/alhaitham2.png", p2 + scale_color_alhaitham(F), width = 6, height = 3)
ggsave("out/ayaka1.png", p1 + scale_fill_ayaka(), width = 6, height = 3)
ggsave("out/ayaka2.png", p2 + scale_color_ayaka(F), width = 6, height = 3)
ggsave("out/bennett1.png", p1 + scale_fill_bennett(), width = 6, height = 3)
ggsave("out/bennett2.png", p2 + scale_color_bennett(F), width = 6, height = 3)
ggsave("out/collei1.png", p1 + scale_fill_collei(), width = 6, height = 3)
ggsave("out/collei2.png", p2 + scale_color_collei(F), width = 6, height = 3)
ggsave("out/diona1.png", p1 + scale_fill_diona(), width = 6, height = 3)
ggsave("out/diona2.png", p2 + scale_color_diona(F), width = 6, height = 3)
ggsave("out/dori1.png", p1 + scale_fill_dori(), width = 6, height = 3)
ggsave("out/dori2.png", p2 + scale_color_dori(F), width = 6, height = 3)
ggsave("out/faruzan1.png", p1 + scale_fill_faruzan(), width = 6, height = 3)
ggsave("out/faruzan2.png", p2 + scale_color_faruzan(F), width = 6, height = 3)
ggsave("out/ganyu1.png", p1 + scale_fill_ganyu(), width = 6, height = 3)
ggsave("out/ganyu2.png", p2 + scale_color_ganyu(F), width = 6, height = 3)
ggsave("out/itto1.png", p1 + scale_fill_itto(), width = 6, height = 3)
ggsave("out/itto2.png", p2 + scale_color_itto(F), width = 6, height = 3)
ggsave("out/jean1.png", p1 + scale_fill_jean(), width = 6, height = 3)
ggsave("out/jean2.png", p2 + scale_color_jean(F), width = 6, height = 3)
ggsave("out/jin1.png", p1 + scale_fill_jin(), width = 6, height = 3)
ggsave("out/jin2.png", p2 + scale_color_jin(F), width = 6, height = 3)
ggsave("out/kazuha1.png", p1 + scale_fill_kazuha(), width = 6, height = 3)
ggsave("out/kazuha2.png", p2 + scale_color_kazuha(F), width = 6, height = 3)
ggsave("out/keqing1.png", p1 + scale_fill_keqing(), width = 6, height = 3)
ggsave("out/keqing2.png", p2 + scale_color_keqing(F), width = 6, height = 3)
ggsave("out/klee1.png", p1 + scale_fill_klee(), width = 6, height = 3)
ggsave("out/klee2.png", p2 + scale_color_klee(F), width = 6, height = 3)
ggsave("out/kokomi1.png", p1 + scale_fill_kokomi(), width = 6, height = 3)
ggsave("out/kokomi2.png", p2 + scale_color_kokomi(F), width = 6, height = 3)
ggsave("out/miko1.png", p1 + scale_fill_miko(), width = 6, height = 3)
ggsave("out/miko2.png", p2 + scale_color_miko(F), width = 6, height = 3)
ggsave("out/nahida1.png", p1 + scale_fill_nahida(), width = 6, height = 3)
ggsave("out/nahida2.png", p2 + scale_color_nahida(F), width = 6, height = 3)
ggsave("out/nilou1.png", p1 + scale_fill_nilou(), width = 6, height = 3)
ggsave("out/nilou2.png", p2 + scale_color_nilou(F), width = 6, height = 3)
ggsave("out/noelle1.png", p1 + scale_fill_noelle(), width = 6, height = 3)
ggsave("out/noelle2.png", p2 + scale_color_noelle(F), width = 6, height = 3)
ggsave("out/razor1.png", p1 + scale_fill_razor(), width = 6, height = 3)
ggsave("out/razor2.png", p2 + scale_color_razor(F), width = 6, height = 3)
ggsave("out/sayu1.png", p1 + scale_fill_sayu(), width = 6, height = 3)
ggsave("out/sayu2.png", p2 + scale_color_sayu(F), width = 6, height = 3)
ggsave("out/shenhe1.png", p1 + scale_fill_shenhe(), width = 6, height = 3)
ggsave("out/shenhe2.png", p2 + scale_color_shenhe(F), width = 6, height = 3)
ggsave("out/shogun1.png", p1 + scale_fill_shogun(), width = 6, height = 3)
ggsave("out/shogun2.png", p2 + scale_color_shogun(F), width = 6, height = 3)
ggsave("out/sucrose1.png", p1 + scale_fill_sucrose(), width = 6, height = 3)
ggsave("out/sucrose2.png", p2 + scale_color_sucrose(F), width = 6, height = 3)
ggsave("out/tao1.png", p1 + scale_fill_tao(), width = 6, height = 3)
ggsave("out/tao2.png", p2 + scale_color_tao(F), width = 6, height = 3)
ggsave("out/tighnari1.png", p1 + scale_fill_tighnari(), width = 6, height = 3)
ggsave("out/tighnari2.png", p2 + scale_color_tighnari(F), width = 6, height = 3)
ggsave("out/venti1.png", p1 + scale_fill_venti(), width = 6, height = 3)
ggsave("out/venti2.png", p2 + scale_color_venti(F), width = 6, height = 3)
ggsave("out/xiangling1.png", p1 + scale_fill_xiangling(), width = 6, height = 3)
ggsave("out/xiangling2.png", p2 + scale_color_xiangling(F), width = 6, height = 3)
ggsave("out/xiao1.png", p1 + scale_fill_xiao(), width = 6, height = 3)
ggsave("out/xiao2.png", p2 + scale_color_xiao(F), width = 6, height = 3)
ggsave("out/yoimiya1.png", p1 + scale_fill_yoimiya(), width = 6, height = 3)
ggsave("out/yoimiya2.png", p2 + scale_color_yoimiya(F), width = 6, height = 3)
ggsave("out/zhongli1.png", p1 + scale_fill_zhongli(), width = 6, height = 3)
ggsave("out/zhongli2.png", p2 + scale_color_zhongli(F), width = 6, height = 3)
